development:
  adapter: postgresql
  encoding: unicode
  database: mini-store_development
  pool: 5
  username: simonweber
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: mini-store_test
  pool: 5
  username: simonweber
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: mini-store_production
  pool: 5
  username: simonweber
  password:
